# Generated by Django 6.0.6 on 2026-06-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('passing_year', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.jobseekerreg')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.jobseekerreg')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.jobseekerreg')),
            ],
        ),
    ]
